name: sample-action

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string
jobs:
  auto-deploy:
    name: Auto-deploy
    if: github.ref == 'refs/heads/master' || github.head_ref == 'master'
    runs-on: ubuntu-latest
    steps: 
      - id: echo
        name: echo
        shell: bash
        run: |
          echo ${{inputs.text}}
