name: sample-action

on: 
  workflow_call:
    inputs:
      text:
        required: true
        type: string
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "step1"
        run: echo "${{inputs.text}}"
